[general]
import = ["~/.config/alacritty/colors.toml"]

[font]
normal = { family = "JetBrains Mono Nerd Font", style = "Normal" }
bold = { family = "JetBrains Mono Nerd Font", style = "Bold" }
size = 11
offset = { x = 0, y = 2 }

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
decorations = "None"

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
