## COLORSCHEME: Kanagawa Wave

# Backgrounds
set -g @kanagawa_bg_dim '#1f1f28'
set -g @kanagawa_bg0 '#1f1f28'
set -g @kanagawa_bg1 '#2a2a37'
set -g @kanagawa_bg2 '#363646'
set -g @kanagawa_bg3 '#54546d'
set -g @kanagawa_bg4 '#727169'
set -g @kanagawa_bg5 '#8a8980'

# Contextual backgrounds
set -g @kanagawa_bg_visual '#2d4f67'
set -g @kanagawa_bg_red '#43242b'
set -g @kanagawa_bg_green '#2f3b2f'
set -g @kanagawa_bg_blue '#223249'
set -g @kanagawa_bg_yellow '#49443c'

# Foreground & accents
set -g @kanagawa_fg '#dcd7ba'
set -g @kanagawa_red '#c34043'
set -g @kanagawa_orange '#ffa066'
set -g @kanagawa_yellow '#c0a36e'
set -g @kanagawa_green '#76946a'
set -g @kanagawa_aqua '#6a9589'
set -g @kanagawa_blue '#7e9cd8'
set -g @kanagawa_purple '#957fb8'

# Greys / neutrals
set -g @kanagawa_grey0 '#a6a69c'
set -g @kanagawa_grey1 '#c8c093'
set -g @kanagawa_grey2 '#dcd7ba'

# Status line
set -g @kanagawa_statusline1 '#76946a'
set -g @kanagawa_statusline2 '#c8c093'
set -g @kanagawa_statusline3 '#c34043'

set-option -g status "on"
set -g status-interval 2

set-option -g status-fg '#dcd7ba' # fg
set-option -g status-bg '#1f1f28' # bg0

set-option -g mode-style fg='#{@kanagawa_purple}',bg='#{@kanagawa_bg_red}' 

# default statusbar colors
set-option -g status-style fg='#{@kanagawa_fg}',bg='#{@kanagawa_bg_dim}',default 

# ---- Windows ----
# default window title colors
set-window-option -g window-status-style fg='#{@kanagawa_bg5}',bg='#{@kanagawa_bg0}' 

# default window with an activity alert
set-window-option -g window-status-activity-style 'bg=#{@kanagawa_bg1},fg=#{@kanagawa_bg3}' 

# active window title colors
set-window-option -g window-status-current-style fg='#{@kanagawa_fg}',bg='#{@kanagawa_bg_green}' 

# ---- Pane ----
# pane borders
set-option -g pane-border-style fg='#{@kanagawa_bg1}' 
set-option -g pane-active-border-style 'fg=#{@kanagawa_blue}' 

# pane number display
set-option -g display-panes-active-colour '#7e9cd8' # blue
set-option -g display-panes-colour '#ffa066' # orange

# ---- Command ----
# message info
set-option -g message-style fg='#{@kanagawa_statusline3}',bg='#{@kanagawa_bg_dim}' 

# writing commands inactive
set-option -g message-command-style 'fg=#{@kanagawa_bg3},bg=#{@kanagawa_bg1}' 

# ---- Miscellaneous ----
# clock
set-window-option -g clock-mode-colour '#7e9cd8' #blue

# bell
set-window-option -g window-status-bell-style fg='#{@kanagawa_bg0}',bg='#{@kanagawa_statusline3}' 

# ---- Formatting ----
set-option -g status-left-style none
set -g status-left-length 60
# bg here is kanagawa_green, fg is the dark bg0_hard for contrast on the tag
set -g status-left "#[fg=#1f1f28,bg=#76946a,bold] #S #[fg=#76946a,bg=#1f1f28,nobold,nounderscore,noitalics]"

set-option -g status-right-style none
set -g status-right-length 150
set -g status-right ' '

set -g window-status-separator '#[fg=#{@kanagawa_grey2},bg=#{@kanagawa_bg0}] '
set -g window-status-format "#[fg=#{@kanagawa_grey0},bg=#{@kanagawa_bg0}] #I  #[fg=#{@kanagawa_grey0},bg=#{@kanagawa_bg0}]#W "
set -g window-status-current-format "#[fg=#{@kanagawa_bg0},bg=#{@kanagawa_bg_green}]#[fg=#{@kanagawa_fg},bg=#{@kanagawa_bg_green}] #I  #[fg=#{@kanagawa_fg},bg=#{@kanagawa_bg_green},bold]#W #[fg=#{@kanagawa_bg_green},bg=#{@kanagawa_bg0},nobold]"
