## COLORSCHEME: Gruvbox Material Dark Soft
set -g @gruvbox_bg_dim '#242424'
set -g @gruvbox_bg0 '#32302f'
set -g @gruvbox_bg1 '#3c3836'
set -g @gruvbox_bg2 '#3c3836'
set -g @gruvbox_bg3 '#504945'
set -g @gruvbox_bg4 '#504945'
set -g @gruvbox_bg5 '#665c54'
set -g @gruvbox_bg_visual '#442e2d'
set -g @gruvbox_bg_red '#442e2d'
set -g @gruvbox_bg_green '#39392d'
set -g @gruvbox_bg_blue '#2e3b3b'
set -g @gruvbox_bg_yellow '#473c2e'

set -g @gruvbox_fg '#d4be98'
set -g @gruvbox_red '#ea6962'
set -g @gruvbox_orange '#e78a4e'
set -g @gruvbox_yellow '#d8a657'
set -g @gruvbox_green '#a9b665'
set -g @gruvbox_aqua '#89b482'
set -g @gruvbox_blue '#7daea3'
set -g @gruvbox_purple '#d3869b'
set -g @gruvbox_grey0 '#7c6f64'
set -g @gruvbox_grey1 '#928374'
set -g @gruvbox_grey2 '#a89984'
set -g @gruvbox_statusline1 '#a9b665'
set -g @gruvbox_statusline2 '#d4be98'
set -g @gruvbox_statusline3 '#ea6962'

set-option -g status "on"
set -g status-interval 2

set-option -g status-fg '#d4be98' # fg
set-option -g status-bg '#32302f' # bg0

set-option -g mode-style fg='#{@gruvbox_purple}',bg='#{@gruvbox_bg_red}' 

# default statusbar colors
set-option -g status-style fg='#{@gruvbox_fg}',bg='#{@gruvbox_bg_dim}',default 

# ---- Windows ----
# default window title colors
set-window-option -g window-status-style fg='#{@gruvbox_bg5}',bg='#{@gruvbox_bg0}' 

# default window with an activity alert
set-window-option -g window-status-activity-style 'bg=#{@gruvbox_bg1},fg=#{@gruvbox_bg3}' 

# active window title colors
set-window-option -g window-status-current-style fg='#{@gruvbox_fg}',bg='#{@gruvbox_bg_green}' 

# ---- Pane ----
# pane borders
set-option -g pane-border-style fg='#{@gruvbox_bg1}' 
set-option -g pane-active-border-style 'fg=#{@gruvbox_blue}' 

# pane number display
set-option -g display-panes-active-colour '#7daea3' # blue
set-option -g display-panes-colour '#e78a4e' # orange

# ---- Command ----
# message info
set-option -g message-style fg='#{@gruvbox_statusline3}',bg='#{@gruvbox_bg_dim}' 

# writing commands inactive
set-option -g message-command-style 'fg=#{@gruvbox_bg3},bg=#{@gruvbox_bg1}' 

# ---- Miscellaneous ----
# clock
set-window-option -g clock-mode-colour '#7daea3' #blue

# bell
set-window-option -g window-status-bell-style fg='#{@gruvbox_bg0}',bg='#{@gruvbox_statusline3}' 

# ---- Formatting ----
set-option -g status-left-style none
set -g status-left-length 60
# bg here is gruvbox_green, fg is the dark bg0_hard for contrast on the tag
set -g status-left "#[fg=#1d2021,bg=#a9b665,bold] #S #[fg=#a9b665,bg=#32302f,nobold,nounderscore,noitalics]"

set-option -g status-right-style none
set -g status-right-length 150
set -g status-right ' '

set -g window-status-separator '#[fg=#{@gruvbox_grey2},bg=#{@gruvbox_bg0}] '
set -g window-status-format "#[fg=#{@gruvbox_grey0},bg=#{@gruvbox_bg0}] #I  #[fg=#{@gruvbox_grey0},bg=#{@gruvbox_bg0}]#W "
set -g window-status-current-format "#[fg=#{@gruvbox_bg0},bg=#{@gruvbox_bg_green}]#[fg=#{@gruvbox_fg},bg=#{@gruvbox_bg_green}] #I  #[fg=#{@gruvbox_fg},bg=#{@gruvbox_bg_green},bold]#W #[fg=#{@gruvbox_bg_green},bg=#{@gruvbox_bg0},nobold]"
