## COLORSCHEME: Gruvbox Dark (soft)

set -g @gruvbox_bg_dim '#32302f'
set -g @gruvbox_bg0 '#32302f'
set -g @gruvbox_bg1 '#3c3836'
set -g @gruvbox_bg2 '#504945'
set -g @gruvbox_bg3 '#665c54'
set -g @gruvbox_bg4 '#7c6f64'
set -g @gruvbox_bg5 '#928374'

set -g @gruvbox_bg_visual '#3c3836'
set -g @gruvbox_bg_red '#3c1f1e'
set -g @gruvbox_bg_green '#32361a'
set -g @gruvbox_bg_blue '#0d3138'
set -g @gruvbox_bg_yellow '#3c2f1e'

set -g @gruvbox_fg '#ebdbb2'
set -g @gruvbox_red '#cc241d'
set -g @gruvbox_orange '#d65d0e'
set -g @gruvbox_yellow '#d79921'
set -g @gruvbox_green '#98971a'
set -g @gruvbox_aqua '#689d6a'
set -g @gruvbox_blue '#458588'
set -g @gruvbox_purple '#b16286'

set -g @gruvbox_grey0 '#a89984'
set -g @gruvbox_grey1 '#bdae93'
set -g @gruvbox_grey2 '#d5c4a1'

set -g @gruvbox_statusline1 '#98971a'
set -g @gruvbox_statusline2 '#ebdbb2'
set -g @gruvbox_statusline3 '#cc241d'

set-option -g status "on"
set -g status-interval 2

set-option -g status-fg '#ebdbb2' # fg
set-option -g status-bg '#32302f' # bg0

set-option -g mode-style fg='#{@gruvbox_purple}',bg='#{@gruvbox_bg_red}' 

# default statusbar colors
set-option -g status-style fg='#{@gruvbox_fg}',bg='#{@gruvbox_bg_dim}',default 

# ---- Windows ----
# default window title colors
set-window-option -g window-status-style fg='#{@gruvbox_bg5}',bg='#{@gruvbox_bg0}' 

# default window with an activity alert
set-window-option -g window-status-activity-style 'bg=#{@gruvbox_bg1},fg=#{@gruvbox_bg3}' 

# active window title colors
set-window-option -g window-status-current-style fg='#{@gruvbox_fg}',bg='#{@gruvbox_bg_green}' 

# ---- Pane ----
# pane borders
set-option -g pane-border-style fg='#{@gruvbox_bg1}' 
set-option -g pane-active-border-style 'fg=#{@gruvbox_blue}' 

# pane number display
set-option -g display-panes-active-colour '#458588' # blue
set-option -g display-panes-colour '#d79921' # orange

# ---- Command ----
# message info
set-option -g message-style fg='#{@gruvbox_statusline3}',bg='#{@gruvbox_bg_dim}' 

# writing commands inactive
set-option -g message-command-style 'fg=#{@gruvbox_bg3},bg=#{@gruvbox_bg1}' 

# ---- Miscellaneous ----
# clock
set-window-option -g clock-mode-colour '#458588' #blue

# bell
set-window-option -g window-status-bell-style fg='#{@gruvbox_bg0}',bg='#{@gruvbox_statusline3}' 

# ---- Formatting ----
set-option -g status-left-style none
set -g status-left-length 60
# bg here is gruvbox_green, fg is the dark bg0_hard for contrast on the tag
set -g status-left "#[fg=#32302f,bg=#98971a,bold] #S #[fg=#98971a,bg=#32302f,nobold,nounderscore,noitalics]"

set-option -g status-right-style none
set -g status-right-length 150
set -g status-right ' '

set -g window-status-separator '#[fg=#{@gruvbox_grey2},bg=#{@gruvbox_bg0}] '
set -g window-status-format "#[fg=#{@gruvbox_grey0},bg=#{@gruvbox_bg0}] #I  #[fg=#{@gruvbox_grey0},bg=#{@gruvbox_bg0}]#W "
set -g window-status-current-format "#[fg=#{@gruvbox_bg0},bg=#{@gruvbox_bg_green}]#[fg=#{@gruvbox_fg},bg=#{@gruvbox_bg_green}] #I  #[fg=#{@gruvbox_fg},bg=#{@gruvbox_bg_green},bold]#W #[fg=#{@gruvbox_bg_green},bg=#{@gruvbox_bg0},nobold]"
