set -g @bg_dim      '#282828'
set -g @bg0         '#32302f'
set -g @bg1         '#3c3836'
set -g @bg2         '#504945'
set -g @bg3         '#665c54'
set -g @bg4         '#7c6f64'
set -g @bg_red      '#fb4934'
set -g @bg_yellow   '#fabd2f'
set -g @bg_green    '#b8bb26'
set -g @bg_blue     '#83a598'
set -g @bg_purple   '#d3869b'
set -g @bg_visual   '#404944'
set -g @fg          '#ebdbb2'
set -g @red         '#fb4934'
set -g @yellow      '#fabd2f'
set -g @green       '#b8bb26'
set -g @blue        '#83a598'
set -g @purple      '#d3869b'
set -g @aqua        '#8ec07c'
set -g @orange      '#fe8019'
set -g @grey0       '#7c6f64'
set -g @grey1       '#928374'
set -g @grey2       '#a89984'
set -g @statusline1 '#a89984'
set -g @statusline2 '#504945'
set -g @statusline3 '#b8bb26'

# ---- General Settings ----
set-option -g status "on"
set -g status-interval 2

set-option -g status-fg '#ebdbb2' # fg
set-option -g status-bg '#32302f' # bg0

set-option -g mode-style fg='#{@purple}',bg='#{@bg2}'

# default statusbar colors
set-option -g status-style fg='#{@fg}',bg='#{@bg0}',default

# ---- Windows ----
# default window title colors
set-window-option -g window-status-style fg='#{@bg4}',bg='#{@bg0}'

# default window with an activity alert
set-window-option -g window-status-activity-style 'bg=#{@bg1},fg=#{@bg3}'

# active window title colors
set-window-option -g window-status-current-style fg='#{@fg}',bg='#{@bg_green}'

# ---- Pane ----
# pane borders
set-option -g pane-border-style fg='#{@bg1}'
set-option -g pane-active-border-style 'fg=#{@blue}'

# pane number display
set-option -g display-panes-active-colour '#83a598' # blue
set-option -g display-panes-colour '#fe8019' # orange

# ---- Command ----
# message info
set-option -g message-style fg='#{@statusline3}',bg='#{@bg_dim}'

# writing commands inactive
set-option -g message-command-style 'fg=#{@bg3},bg=#{@bg1}'

# ---- Miscellaneous ----
# clock
set-window-option -g clock-mode-colour '#83a598' # blue

# bell
set-window-option -g window-status-bell-style fg='#{@bg0}',bg='#{@statusline3}'

# ---- Formatting ----
set-option -g status-left-style none
set -g status-left-length 60
# bg here is statusline1, fg is the dark bg0 for contrast
set -g status-left "#[fg=#32302f,bg=#a89984,bold] #S #[fg=#a89984,bg=#32302f,nobold,nounderscore,noitalics]"

set-option -g status-right-style none
set -g status-right-length 150
set -g status-right ' '

set -g window-status-separator '#[fg=#{@grey2},bg=#{@bg0}] '
set -g window-status-format "#[fg=#{@grey0},bg=#{@bg0}] #I  #[fg=#{@grey0},bg=#{@bg0}]#W "
set -g window-status-current-format "#[fg=#{@bg0},bg=#{@statusline2}]#[fg=#{@statusline1},bg=#{@statusline2}] #I  #[fg=#{@statusline1},bg=#{@statusline2},bold]#W #[fg=#{@statusline2},bg=#{@bg0},nobold]"
