set -g @bg_dim      '#252423'
set -g @bg0         '#32302f'
set -g @bg1         '#3c3836'
set -g @bg2         '#3c3836'
set -g @bg3         '#504945'
set -g @bg4         '#504945'
set -g @bg_visual   '#424a3e'
set -g @fg          '#d4be98'
set -g @red         '#ea6962'
set -g @yellow      '#d8a657'
set -g @green       '#a9b665'
set -g @blue        '#7daea3'
set -g @purple      '#d3869b'
set -g @aqua        '#89b482'
set -g @orange      '#e78a4e'
set -g @grey0       '#7c6f64'
set -g @grey1       '#928374'
set -g @statusline1 '#a89984'
set -g @statusline2 '#ea6962'

# ---- General Settings ----
set-option -g status "on"
set -g status-interval 2

set-option -g status-fg '#d4be98' # fg
set-option -g status-bg '#32302f' # bg0

set-option -g mode-style fg='#{@purple}',bg='#{@bg2}'

# default statusbar colors
set-option -g status-style fg='#{@fg}',bg='#{@bg0}',default

# ---- Windows ----
# default window title colors
set-window-option -g window-status-style fg='#{@bg4}',bg='#{@bg0}'

# default window with an activity alert
set-window-option -g window-status-activity-style 'bg=#{@bg1},fg=#{@bg3}'

# active window title colors
set-window-option -g window-status-current-style fg='#{@fg}',bg='#{@bg_visual}'

# ---- Pane ----
# pane borders
set-option -g pane-border-style fg='#{@bg1}'
set-option -g pane-active-border-style 'fg=#{@blue}'

# pane number display
set-option -g display-panes-active-colour '#7daea3' # blue
set-option -g display-panes-colour '#e78a4e' # orange

# ---- Command ----
# message info
set-option -g message-style fg='#{@statusline2}',bg='#{@bg_dim}'

# writing commands inactive
set-option -g message-command-style 'fg=#{@bg3},bg=#{@bg1}'

# ---- Miscellaneous ----
# clock
set-window-option -g clock-mode-colour '#7daea3' # blue

# bell
set-window-option -g window-status-bell-style fg='#{@bg0}',bg='#{@statusline3}'

# ---- Formatting ----
set-option -g status-left-style none
set -g status-left-length 60
# bg here is statusline1, fg is the dark bg0 for contrast
set -g status-left "#[fg=#32302f,bg=#a89984,bold] #S "

set-option -g status-right-style none
set -g status-right-length 150
set -g status-right ''

set -g window-status-separator ''
set -g window-status-format "#[fg=#{@grey0},bg=#{@bg0}] #I | #[fg=#{@grey0},bg=#{@bg0}]#W "
set -g window-status-current-format "#[fg=#{@grey1},bg=#{@bg3}] #I | #[fg=#{@grey1},bg=#{@bg3},bold,italics]#W "
