set -g @bg_dim      '#ebdbb2'
set -g @bg0         '#f2e5bc'
set -g @bg1         '#eddeb5'
set -g @bg2         '#eddeb5'
set -g @bg3         '#e6d5ae'
set -g @bg4         '#dac9a5'
set -g @bg_visual   '#efd2b3'
set -g @fg          '#3c3836'
set -g @red         '#9d0006'
set -g @yellow      '#b57614'
set -g @green       '#79740e'
set -g @blue        '#076678'
set -g @purple      '#8f3f71'
set -g @aqua        '#427b58'
set -g @orange      '#af3a03'
set -g @grey0       '#a89984'
set -g @grey1       '#928374'
set -g @statusline1 '#7c6f64'
set -g @statusline2 '#a89984'

# ---- General Settings ----
set-option -g status "on"
set -g status-interval 2

set-option -g status-fg '#3c3836' # fg
set-option -g status-bg '#f2e5bc' # bg0

set-option -g mode-style fg='#{@purple}',bg='#{@bg2}'

# default statusbar colors
set-option -g status-style fg='#{@fg}',bg='#{@bg0}',default

# ---- Windows ----
# default window title colors
set-window-option -g window-status-style fg='#{@bg4}',bg='#{@bg0}'

# default window with an activity alert
set-window-option -g window-status-activity-style 'bg=#{@bg1},fg=#{@bg3}'

# active window title colors
set-window-option -g window-status-current-style fg='#{@fg}',bg='#{@bg_visual}'

# ---- Pane ----
# pane borders
set-option -g pane-border-style fg='#{@bg1}'
set-option -g pane-active-border-style 'fg=#{@blue}'

# pane number display
set-option -g display-panes-active-colour '#076678' # blue
set-option -g display-panes-colour '#af3a03' # orange

# ---- Command ----
# message info
set-option -g message-style fg='#{@statusline2}',bg='#{@bg_dim}'

# writing commands inactive
set-option -g message-command-style 'fg=#{@bg3},bg=#{@bg1}'

# ---- Miscellaneous ----
# clock
set-window-option -g clock-mode-colour '#076678' # blue

# bell
set-window-option -g window-status-bell-style fg='#{@bg0}',bg='#{@statusline3}'

# ---- Formatting ----
set-option -g status-left-style none
set -g status-left-length 60
# bg here is statusline1, fg is the dark bg0 for contrast
set -g status-left "#[fg=#f2e5bc,bg=#7c6f64,bold] #S "

set-option -g status-right-style none
set -g status-right-length 150
set -g status-right ''

set -g window-status-separator ''
set -g window-status-format "#[fg=#{@grey0},bg=#{@bg0}] #I | #[fg=#{@grey0},bg=#{@bg0}]#W "
set -g window-status-current-format "#[fg=#{@grey1},bg=#{@bg3}] #I | #[fg=#{@grey1},bg=#{@bg3},bold,italics]#W "
