set -g @bg_dim      '#e5dfc5'
set -g @bg0         '#f3ead3'
set -g @bg1         '#eae4ca'
set -g @bg2         '#e5dfc5'
set -g @bg3         '#ddd8be'
set -g @bg4         '#d8d3ba'
set -g @bg5         '#b9c0ab'
set -g @bg_red      '#fadbd0'
set -g @bg_yellow   '#f1e4c5'
set -g @bg_green    '#e5e6c5'
set -g @bg_blue     '#e1e7dd'
set -g @bg_purple   '#f1ddd4'
set -g @bg_visual   '#e1e4bd'
set -g @fg          '#5c6a72'
set -g @red         '#f85552'
set -g @yellow      '#dfa000'
set -g @green       '#8da101'
set -g @blue        '#3a94c5'
set -g @purple      '#df69ba'
set -g @aqua        '#35a77c'
set -g @orange      '#f57d26'
set -g @grey0       '#a6b0a0'
set -g @grey1       '#939f91'
set -g @grey2       '#829181'
set -g @statusline1 '#8da101'
set -g @statusline2 '#5c6a72'
set -g @statusline3 '#f85552'

set-option -g status "on"
set -g status-interval 2

set-option -g status-fg '#5c6a72' # fg
set-option -g status-bg '#f3ead3' # bg0

set-option -g mode-style fg='#{@purple}',bg='#{@bg_red}' 

# default statusbar colors
set-option -g status-style fg='#{@fg}',bg='#{@bg_dim}',default 

# ---- Windows ----
# default window title colors
set-window-option -g window-status-style fg='#{@bg5}',bg='#{@bg0}' 

# default window with an activity alert
set-window-option -g window-status-activity-style 'bg=#{@bg1},fg=#{@bg3}' 

# active window title colors
set-window-option -g window-status-current-style fg='#{@fg}',bg='#{@bg_green}' 

# ---- Pane ----
# pane borders
set-option -g pane-border-style fg='#{@bg1}' 
set-option -g pane-active-border-style 'fg=#{@blue}' 

# pane number display
set-option -g display-panes-active-colour '#3a94c5' # blue
set-option -g display-panes-colour '#f57d26' # orange

# ---- Command ----
# message info
set-option -g message-style fg='#{@statusline3}',bg='#{@bg_dim}' 

# writing commands inactive
set-option -g message-command-style 'fg=#{@bg3},bg=#{@bg1}' 

# ---- Miscellaneous ----
# clock
set-window-option -g clock-mode-colour '#3a94c5' #blue

# bell
set-window-option -g window-status-bell-style fg='#{@bg0}',bg='#{@statusline3}' 

# ---- Formatting ----
set-option -g status-left-style none
set -g status-left-length 60
# bg here is green, fg is the dark bg0_hard for contrast on the tag
set -g status-left "#[fg=#f3ead3,bg=#8da101,bold] #S #[fg=#8da101,bg=#f3ead3,nobold,nounderscore,noitalics]"

set-option -g status-right-style none
set -g status-right-length 150
set -g status-right ' '

set -g window-status-separator '#[fg=#{@grey2},bg=#{@bg0}] '
set -g window-status-format "#[fg=#{@grey0},bg=#{@bg0}] #I  #[fg=#{@grey0},bg=#{@bg0}]#W "
set -g window-status-current-format "#[fg=#{@bg0},bg=#{@bg_green}]#[fg=#{@fg},bg=#{@bg_green}] #I  #[fg=#{@fg},bg=#{@bg_green},bold]#W #[fg=#{@bg_green},bg=#{@bg0},nobold]"


