set -g @bg_dim      '#d5cea3'
set -g @bg0         '#f2ecbc'
set -g @bg1         '#dcd5ac'
set -g @bg2         '#e5ddb0'
set -g @bg3         '#e7dba0'
set -g @bg4         '#e4d794'
set -g @bg_visual   '#c9cbd1'
set -g @fg          '#545464'
set -g @red         '#c84053'
set -g @yellow      '#77713f'
set -g @green       '#6f894e'
set -g @blue        '#4d699b'
set -g @purple      '#624c83'
set -g @aqua        '#597b75'
set -g @orange      '#b35b79'
set -g @grey0       '#8a8980'
set -g @grey1       '#6f6f6f'
set -g @statusline1 '#4d699b'
set -g @statusline2 '#c84053'

# ---- General Settings ----
set-option -g status "on"
set -g status-interval 2

set-option -g status-fg '#545464' # fg
set-option -g status-bg '#f2ecbc' # bg0

set-option -g mode-style fg='#{@purple}',bg='#{@bg2}'

# default statusbar colors
set-option -g status-style fg='#{@fg}',bg='#{@bg0}',default

# ---- Windows ----
# default window title colors
set-window-option -g window-status-style fg='#{@bg4}',bg='#{@bg0}'

# default window with an activity alert
set-window-option -g window-status-activity-style 'bg=#{@bg1},fg=#{@bg3}'

# active window title colors
set-window-option -g window-status-current-style fg='#{@fg}',bg='#{@bg_visual}'

# ---- Pane ----
# pane borders
set-option -g pane-border-style fg='#{@bg1}'
set-option -g pane-active-border-style 'fg=#{@blue}'

# pane number display
set-option -g display-panes-active-colour '#4d699b' # blue
set-option -g display-panes-colour '#b35b79' # orange

# ---- Command ----
# message info
set-option -g message-style fg='#{@statusline2}',bg='#{@bg_dim}'

# writing commands inactive
set-option -g message-command-style 'fg=#{@bg3},bg=#{@bg1}'

# ---- Miscellaneous ----
# clock
set-window-option -g clock-mode-colour '#4d699b' # blue

# bell
set-window-option -g window-status-bell-style fg='#{@bg0}',bg='#{@statusline3}'

# ---- Formatting ----
set-option -g status-left-style none
set -g status-left-length 60
# bg here is statusline1, fg is the dark bg0 for contrast
set -g status-left "#[fg=#d5cea3,bg=#4d699b,bold] #S "

set-option -g status-right-style none
set -g status-right-length 150
set -g status-right ''

set -g window-status-separator ''
set -g window-status-format "#[fg=#{@grey0},bg=#{@bg0}] #I | #[fg=#{@grey0},bg=#{@bg0}]#W "
set -g window-status-current-format "#[fg=#{@grey1},bg=#{@bg3}] #I | #[fg=#{@grey1},bg=#{@bg3},bold,italics]#W "
