############
# SETTINGS #
############
# Enable mouse mode
set -g mouse on

# Set history to 10,000 lines
set-option -g history-limit 10000

# Start pane at 1
set -g base-index 1
setw -g pane-base-index 1

# Renumber window on removal
set -g renumber-windows on

# Set true color
set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"

# Notify if other windows has activities
setw -g monitor-activity on


###########
# KEYMAPS #
###########

# Change prefix to Ctrl + Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Split panes using v and z
bind v split-window -h
bind z split-window -v
unbind '"'
unbind %

# Navigate pane
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R


###############
#   DESIGNS   #
###############
# Don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# Source theme color
# source "$HOME/.config/tmux/light.conf"
source "$HOME/.config/tmux/dark.conf"

###########
# PLUGINS #
###########
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "tmux-plugins/tmux-yank"
set -g @plugin "christoomey/vim-tmux-navigator"
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Run plugin manager
run "~/.tmux/plugins/tpm/tpm"
